name: Go

on:
  push:
    branches: [ go ]
  pull_request:
    branches: [ go ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Data Structures
      working-directory: ds
      run: go test -v ./...
      
    - name: Test Algorithms
      working-directory: algorithms
      run: go test -v ./...
